# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - 30daysinger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_8f58a46aee7246b295a0726be5e3e164 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_381458260c8b4aa58ffba78ed8ced682 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8f58a46aee7246b295a0726be5e3e164 }}/30daysinger:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '30daysinger'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1f37f749996148a2ab70b1a9918797c1 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8f58a46aee7246b295a0726be5e3e164 }}/30daysinger:${{ github.sha }}'