# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - 30daysinger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_b8f88cb9b8294a1293811e2225f1fa6b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4cb77d9225b841289cbe25b8e955a236 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b8f88cb9b8294a1293811e2225f1fa6b }}/nginx:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '30daysinger'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_187111eb7d77469a86f005c2167d2f45 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b8f88cb9b8294a1293811e2225f1fa6b }}/nginx:${{ github.sha }}'